---

- name: Log in to Bitwarden
  command: "bw login --apikey {{ bitwarden_api_key }}"
  register: bw_login
  no_log: false
  ignore_errors: true

- name: Check if Bitwarden login was successful
  fail:
    msg: "Bitwarden login failed. Please check your API key."
  when: "'You are now logged in!' not in bw_login.stdout"

- name: Get Bitwarden session key
  command: "bw unlock --raw --password {{ bitwarden_api_key }}"
  register: bw_session
  no_log: true

- name: Set Bitwarden session key as environment variable
  set_fact:
    BW_SESSION: "{{ bw_session.stdout }}"
  no_log: true

- name: Retrieve Terraform token from Bitwarden
  command: "bw get password ocm-api --session {{ BW_SESSION }}"
  register: terraform_token
  no_log: true

- name: Retrieve admin password from Bitwarden
  command: "bw get password admin --session {{ BW_SESSION }}"
  register: admin_password
  no_log: true

- name: Set Terraform environment variables
  shell: |
    export TF_VAR_token="{{ terraform_token.stdout }}"
    export TF_VAR_admin_password="{{ admin_password.stdout }}"
  environment:
    TF_VAR_token: "{{ terraform_token.stdout }}"
    TF_VAR_admin_password: "{{ admin_password.stdout }}"

- name: Deploy the TF resources
  community.general.terraform:
    project_path: '{{ project_dir }}'
    state: present