---

- name: Set Terraform environment variables
  shell: |
    export TF_VAR_token="{{ terraform_token.stdout }}"
    export TF_VAR_admin_password="{{ admin_password.stdout }}"
  environment:
    TF_VAR_token: "{{ terraform_token.stdout }}"
    TF_VAR_admin_password: "{{ admin_password.stdout }}"

- name: Deploy the TF resources
  community.general.terraform:
    project_path: "{{ tf_project_path }}"
    state: present
    variables_files:
      - "{{ tf_project_path }}/main.tfvars"
    variables:
      token: "{{ terraform_token.stdout }}"
      admin_password: "{{ admin_password.stdout }}"

# need these vars set via vault
# - tf_token
# - tf_project_path
# - admin_password