- name: Login to OCP cluster
  community.okd.openshift_auth:
    host: "{{ create_workshop_cluster_api_url }}"
    username: "{{ create_workshop_admin_user }}"
    password: "{{ create_workshop_admin_pw }}"
    verify_ssl: false
  register: login
  retries: 10
  delay: 60

- name: Fetch the Ingress resource
  community.kubernetes.k8s_info:
    host: "{{ create_workshop_cluster_api_url }}"
    api_key: "{{ login.openshift_auth.api_key }}"
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: ingress_info

- name: Extract the domain from the Ingress resource
  set_fact:
    openshift_domain: "{{ ingress_info.resources[0].spec.domain | regex_replace('^apps\\.', '') }}"

- name: Waiting for OpenShift Healthy State - Can Take up to 12-15 Minutes
  community.kubernetes.k8s_info:
    host: "{{ create_workshop_cluster_api_url }}"
    api_key: "{{ login.openshift_auth.api_key }}"
    api_version: v1
    kind: Pod
  register: pod_info
  until:
    - pod_info.resources is defined
    - pod_info.resources | length > 0
    - pod_info.resources | selectattr('status.phase', 'equalto', 'Pending') | length == 0
  retries: 40
  delay: 30

- name: Workshop
  vars:
    api_url: "{{ create_workshop_cluster_api_url }}"
    token: "{{ login.openshift_auth.api_key }}"
    validate_certs: False
    domain: "{{ openshift_domain }}"
    gitops:
      namespace: "openshift-gitops"
    workshop:
      chart:
        name: "rhoai-devex-mobb"
        repo: "https://poc-examples.github.io/workshops"
        version: "0.1.12"
  ansible.builtin.include_role:
    name: workshop
  collections:
    - bootstrap.workshop

- name: Secrets Management
  vars:
    domain: "{{ openshift_domain }}"
    token: "{{ login.openshift_auth.api_key }}"
    api_url: "{{ create_workshop_cluster_api_url }}"
    validate_certs: False
    secrets:
      vault:
        enabled: true
      namespace: secrets-manager
      pushSecrets: []
  ansible.builtin.import_role:
    name: secrets-manager
  collections:
    - bootstrap.workshop