---
- name: "Init"
  hosts: localhost
  connection: local
  gather_facts: true
  tags:
    - always

  tasks:
    - name: "Set a state fact"
      ansible.builtin.set_fact:
        state: present

- name: Install ROSA HCP cluster
  hosts: localhost
  connection: local
  roles:
    - role: rosa_cluster
      vars:
        rosa_cluster_tf_vars:
          hcp: "true"
    - role: install_rhoai_components
      vars:
        install_rhoai_components_admin_user: "admin"
        install_rhoai_components_admin_pw: "{{ rosa_cluster_tf_vars.admin_password }}"
        install_rhoai_components_cluster_api_url: "{{ rosa_cluster_api_url }}"
