---
- name:         "init"
  hosts:        localhost
  connection:   local
  gather_facts: true
  tags:
    - always

  tasks:
    - name: "set a state fact"
      ansible.builtin.set_fact:
        state: present

- name: Install ARO cluster
  hosts: localhost
  connection:   local
  roles:
    - role: aro_cluster
    - role: install_rhoai_components
      vars:
        admin_pw: "{{ ocp_password }}"
        admin_user: "{{ ocp_username }}"
        cluster_api_url: "{{ cluster_api_url }}"