---
- name: Init
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: ./virtualenv/bin/python
  tags:
    - always

  tasks:
    - name: "Set a state fact"
      ansible.builtin.set_fact:
        state: absent

- name: Destroy cluster
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: ./virtualenv/bin/python
  roles:
    - role: rosa_cluster
      when: cluster_type in ['rosa_hcp','rosa']
    - role: aro_cluster
      when: cluster_type == 'aro'