---
- name:         "init"
  hosts:        localhost
  connection:   local
  gather_facts: true
  tags:
    - always

  tasks:
    - name: "set a state fact"
      ansible.builtin.set_fact:
        state: absent

- name: Install ARO cluster
  hosts: localhost
  connection:   local
  roles:
    - role: aro_cluster
