---
- name: Init
  hosts: localhost
  connection: local
  gather_facts: true
  tags:
    - always

- name: Install RHOAI in cluster
  hosts: localhost
  # vars_files:
  #   - vars/bitwarden_creds.yml

  roles:
    - role: install_rhoai_components
      vars:
        install_rhoai_components_admin_user: "admin"
        install_rhoai_components_admin_pw: "{{ tf_vars.admin_password }}"
        install_rhoai_components_cluster_api_url: "{{ rosa_cluster_api_url }}"
