---
- name: Init
  hosts: localhost
  connection: local
  gather_facts: true
  tags:
    - always
  vars:
    ansible_python_interpreter: ./virtualenv/bin/python

- name: Install RHOAI in cluster
  hosts: localhost
  vars:
    ansible_python_interpreter: ./virtualenv/bin/python

  roles:
    - role: install_rhoai_components
      vars:
        install_rhoai_components_admin_user: "admin"
        install_rhoai_components_admin_pw: "{{ tf_vars.admin_password }}"
        install_rhoai_components_cluster_api_url: "{{ rosa_cluster_api_url }}"
