---
- name:         "init"
  hosts:        localhost
  connection:   local
  gather_facts: true
  tags:
    - always

- name: Install ROSA HCP cluster
  hosts: localhost
  # vars_files:
  #   - vars/bitwarden_creds.yml

  roles:
    - role: install_rhoai_components
      vars:
        admin_user: "admin"
        admin_pw: "{{ tf_vars.admin_password }}"
        cluster_api_url: "{{ rosa_cluster_api_url }}"
