---

collections:
  - name: amazon.aws
  - name: ansible.utils
  - name: bitwarden.secrets
  - name: community.aws
  - name: community.general
  - name: community.kubernetes
  - name: community.okd
  - name: kubernetes.core
  - name: cloud.terraform
  - name: azure.azcollection

  - name: bootstrap.workshop
    source: https://github.com/poc-examples/ansible-collections.git#/bootstrap/workshop
    type: git
    version: main
