---
- name: install nfd terminal operator
  include_role:
    name: install_operator
  vars:
    operator_name: rhods-operator
    operator_namespace: redhat-ods-operator
    operator_channel: fast
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace
    operator_wait: true

# - name: Create Subscription for OpenShift AI Operator
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     state: present
#     definition:
#       apiVersion: operators.coreos.com/v1alpha1
#       kind: Subscription
#       metadata:
#         name: rhods-operator
#         namespace: redhat-ods-operator
#       spec:
#         channel: fast
#         installPlanApproval: Automatic
#         name: rhods-operator
#         source: redhat-operators
#         sourceNamespace: openshift-marketplace

- name: Wait for OpenShift AI Operator to be deployed
  kubernetes.core.k8s_info:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    kind: subscription
    api_version: operators.coreos.com/v1alpha1
    name: rhods-operator
    namespace: redhat-ods-operator
    wait_condition:
      reason: AllCatalogSourcesHealthy
      status: False
      type: CatalogSourcesUnhealthy
    wait_sleep: 10
    wait_timeout: 360
  no_log: true

- name: Create Data Science Cluster
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: datasciencecluster.opendatahub.io/v1
      kind: DataScienceCluster
      metadata:
        name: default-dsc
        labels:
          app.kubernetes.io/created-by: rhods-operator
          app.kubernetes.io/instance: default-dsc
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: datasciencecluster
          app.kubernetes.io/part-of: rhods-operator
      spec:
        components:
          codeflare:
            managementState: Managed
          dashboard:
            managementState: Managed
          datasciencepipelines:
            managementState: Managed
          kserve:
            serving:
              ingressGateway:
                certificate:
                  type: OpenshiftDefaultIngress
              managementState: Managed
          kueue:
            managementState: Managed
          modelmeshserving:
            managementState: Managed
          ray:
            managementState: Managed
          workbenches:
            managementState: Managed

- name: Wait for OpenShift Data Science Cluster
  kubernetes.core.k8s_info:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    kind: Pod
    namespace: redhat-ods-applications
    label_selectors:
      - "app=rhods-dashboard"
    wait_sleep: 10
    wait_timeout: 360
    wait: true

- name: create accelorator profile for nvidia
  when: install_rhoai_components_nvidia_gpus | bool
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: dashboard.opendatahub.io/v1
      kind: AcceleratorProfile
      metadata:
        name: nvidia-gpu
        namespace: redhat-ods-applications
      spec:
        displayName: NVIDIA GPU
        enabled: true
        identifier: nvidia.com/gpu
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists

- name: Fetch Red Hat OpenShift AI url
  kubernetes.core.k8s_info:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    kind: Route
    namespace: redhat-ods-applications
    name: rhods-dashboard
  register: _rhods_dashboard

- name: Set RHOAI dashboard route fact
  ansible.builtin.set_fact:
    rhoai_route: "{{ _rhods_dashboard.resources[0].spec.host }}"
