---

- name: Ensure the gpu-operator namespace exists
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: gpu-operator

- name: Create OperatorGroup for GPU Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: gpu-operator-group
        namespace: gpu-operator
      spec:
        targetNamespaces:
          - gpu-operator

- name: Create Subscription for GPU Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: nvidia-gpu-operator
        namespace: gpu-operator
      spec:
        channel: stable
        name: gpu-operator-certified
        source: certified-operators
        sourceNamespace: openshift-marketplace