---
- name: install web terminal operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: web-terminal
    install_operator_namespace: openshift-operators
    install_operator_channel: fast
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace

- name: install service mesh operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: servicemeshoperator
    install_operator_namespace: openshift-operators
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace

- name: install openshift pipelines operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: openshift-pipelines-operator-rh
    install_operator_namespace: openshift-operators
    install_operator_channel: latest
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace

- name: install serverless operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: serverless-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace

- name: install authorino operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: authorino-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_catalog: community-operators
    install_operator_source_namespace: openshift-marketplace

- name: install distributed tracing operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: jaeger-product
    install_operator_csv_nameprefix: jaeger-operator
    install_operator_namespace: openshift-distributed-tracing
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace

- name: install gitops operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: openshift-gitops-operator
    install_operator_namespace: openshift-gitops-operator
    install_operator_channel: latest
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace
    install_operator_wait: true

- name: Wait for OpenShift GitOps instance to be deployed
  kubernetes.core.k8s_info:
    kind: Pod
    wait: true
    namespace: openshift-gitops
    label_selectors:
      - "app.kubernetes.io/name=openshift-gitops-application-controller"
    wait_sleep: 10
    wait_timeout: 360
  no_log: true

- name: Give permissions to OpenShift GitOps
  community.okd.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        creationTimestamp: null
        name: gitops-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
          - kind: ServiceAccount
            name: openshift-gitops-argocd-application-controller
            namespace: openshift-gitops

- name: install elasticsearch operator if OCP > 4.15
  when: _ocp_version is version('4.15', '<')
  include_role:
    name: install_operator
  vars:
    install_operator_name: elasticsearch-operator
    install_operator_namespace: openshift-logging
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_source_namespace: openshift-marketplace
    install_operator_wait: true
