---

- name: install web terminal operator
  include_role:
    name: install_operator
  vars:
    operator_name: nvidia-gpu-operator
    operator_package: gpu-operator-certified
    operator_namespace: nvidia-gpu-operator
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: certified-operators
    operator_source_namespace: openshift-marketplace
    operator_manage_namespaces: ["nvidia-gpu-operator"]
    operator_wait: true

# - name: Create Subscription for GPU Operator
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     state: present
#     definition:
#       apiVersion: operators.coreos.com/v1alpha1
#       kind: Subscription
#       metadata:
#         name: nvidia-gpu-operator
#         namespace: gpu-operator
#       spec:
#         channel: stable
#         name: gpu-operator-certified
#         source: certified-operators
#         sourceNamespace: openshift-marketplace


# - name: Wait for Nvidia GPU Operator
#   kubernetes.core.k8s_info:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     kind: subscription
#     api_version: operators.coreos.com/v1alpha1
#     # wait: true
#     name: nvidia-gpu-operator
#     namespace: gpu-operator
#     wait_condition:
#       reason: AllCatalogSourcesHealthy
#       status: False
#       type: CatalogSourcesUnhealthy
#     wait_sleep: 10
#     wait_timeout: 360
#   no_log: true

  # kubernetes.core.k8s_info:
  #   host: "{{ host }}"
  #   api_key: "{{ api_key }}"
  #   kind: Pod
  #   wait: true
  #   namespace: gpu-operator
  #   label_selectors:
  #     - "app=gpu-operator"
  #   wait_sleep: 10
  #   wait_timeout: 360

# - name: create NFD for nvidia
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     state: present
#     definition:
#       kind: NodeFeatureDiscovery
#       apiVersion: nfd.openshift.io/v1
#       metadata:
#         name: nfd-instance
#         namespace: openshift-nfd
#       spec:
#         customConfig:
#           configData: ""
#         operand:
#           image: >-
#             registry.redhat.io/openshift4/ose-node-feature-discovery@sha256:07658ef3df4b264b02396e67af813a52ba416b47ab6e1d2d08025a350ccd2b7b
#           servicePort: 12000
#         workerConfig:
#           configData: |
#             core:
#               sleepInterval: 60s
#               pci:
#                 deviceClassWhitelist:
#                   - "0200"
#                   - "03"
#                   - "12"
#                 deviceLabelFields:
#                   - "vendor"

- name: create cluster policy for nvidia
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: nvidia.com/v1
      kind: ClusterPolicy
      metadata:
        name: gpu-cluster-policy
      spec:
        migManager:
          enabled: true
        operator:
          defaultRuntime: crio
          initContainer: {}
          runtimeClass: nvidia
          deployGFD: true
        dcgm:
          enabled: true
        gfd: {}
        dcgmExporter:
          config:
            name: ''
        driver:
          licensingConfig:
            nlsEnabled: false
            configMapName: ''
          certConfig:
            name: ''
          kernelModuleConfig:
            name: ''
          repoConfig:
            configMapName: ''
          virtualTopology:
            config: ''
          enabled: true
          use_ocp_driver_toolkit: true
        devicePlugin: {}
        mig:
          strategy: single
        validator:
          plugin:
            env:
              - name: WITH_WORKLOAD
                value: 'true'
        nodeStatusExporter:
          enabled: true
        daemonsets: {}
        toolkit:
          enabled: true