---

# - name: Create OperatorGroup
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     definition:
#       apiVersion: operators.coreos.com/v1
#       kind: OperatorGroup
#       metadata:
#         name: global-operators
#         namespace: openshift-operators
#       spec: {}

- name: install web terminal operator
  include_role:
    name: install_operator
  vars:
    operator_name: web-terminal
    operator_namespace: openshift-operators
    operator_channel: fast
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace

- name: install service mesh operator
  include_role:
    name: install_operator
  vars:
    operator_name: servicemeshoperator
    operator_namespace: openshift-operators
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace

- name: install openshift pipelines operator
  include_role:
    name: install_operator
  vars:
    operator_name: openshift-pipelines-operator-rh
    operator_namespace: openshift-operators
    operator_channel: latest
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace

- name: install serverless operator
  include_role:
    name: install_operator
  vars:
    operator_name: serverless-operator
    operator_namespace: openshift-operators
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace

- name: install authorino operator
  include_role:
    name: install_operator
  vars:
    operator_name: authorino-operator
    operator_namespace: openshift-operators
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: community-operators
    operator_source_namespace: openshift-marketplace

- name: install distributed tracing operator
  include_role:
    name: install_operator
  vars:
    operator_name: jaeger-product
    operator_namespace: openshift-distributed-tracing
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace

- name: install gitops operator
  include_role:
    name: install_operator
  vars:
    operator_name: openshift-gitops-operator
    operator_namespace: openshift-gitops-operator
    operator_channel: latest
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace
    operator_wait: true

- name: Wait for OpenShift GitOps instance to be deployed
  kubernetes.core.k8s_info:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    kind: Pod
    wait: true
    namespace: openshift-gitops
    label_selectors:
      - "app.kubernetes.io/name=openshift-gitops-application-controller"
    wait_sleep: 10
    wait_timeout: 360
  no_log: true

- name: Give permissions to OpenShift GitOps
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        creationTimestamp: null
        name: gitops-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
          - kind: ServiceAccount
            name: openshift-gitops-argocd-application-controller
            namespace: openshift-gitops

- name: install elasticsearch operator if OCP > 4.15
  when: _ocp_version is version('4.15', '<')
  include_role:
    name: install_operator
  vars:
    operator_name: elasticsearch-operator
    operator_namespace: openshift-logging
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace
    operator_wait: true
