---

- name: install nfd terminal operator
  include_role:
    name: install_operator
  vars:
    operator_name: nfd
    operator_namespace: openshift-nfd
    operator_channel: stable
    operator_install_plan_approval: Automatic
    operator_source: redhat-operators
    operator_source_namespace: openshift-marketplace
    operator_manage_namespaces: ["openshift-nfd"]
    operator_wait: true

- name: Create NFD Instance
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: nfd.openshift.io/v1
      kind: NodeFeatureDiscovery
      metadata:
        name: nfd-instance
        namespace: openshift-nfd
      spec:
        operand:
          image: quay.io/openshift/origin-node-feature-discovery:4.15
          imagePullPolicy: Always
          servicePort: 12000
        workerConfig:
          configData: |
            core:
              sleepInterval: 60s
            sources:
              cpu:
                cpuid:
                  attributeBlacklist:
                    - "BMI1"
                    - "BMI2"
                    - "CLMUL"
                    - "CMOV"
                    - "CX16"
                    - "ERMS"
                    - "F16C"
                    - "HTT"
                    - "LZCNT"
                    - "MMX"
                    - "MMXEXT"
                    - "NX"
                    - "POPCNT"
                    - "RDRAND"
                    - "RDSEED"
                    - "RDTSCP"
                    - "SGX"
                    - "SSE"
                    - "SSE2"
                    - "SSE3"
                    - "SSE4.1"
                    - "SSE4.2"
                    - "SSSE3"
                  attributeWhitelist:
              kernel:
                kconfigFile: "/path/to/kconfig"
                configOpts:
                  - "NO_HZ"
                  - "X86"
                  - "DMI"
              pci:
                deviceClassWhitelist:
                  - "0200"
                  - "03"
                  - "12"
                deviceLabelFields:
                  - "class"
