---

- name: install nvidia gpu operator
  include_role:
    name: install_operator
  vars:
    install_operator_name: gpu-operator-certified
    install_operator_namespace: nvidia-gpu-operator
    install_operator_channel: stable
    install_operator_install_plan_approval: Automatic
    install_operator_catalog: certified-operators
    install_operator_source_namespace: openshift-marketplace
    install_operator_manage_namespaces: ["nvidia-gpu-operator"]
    install_operator_wait: true

- name: create cluster policy for nvidia
  community.okd.k8s:
    state: present
    definition:
      apiVersion: nvidia.com/v1
      kind: ClusterPolicy
      metadata:
        name: gpu-cluster-policy
      spec:
        migManager:
          enabled: true
        operator:
          defaultRuntime: crio
          initContainer: {}
          runtimeClass: nvidia
          deployGFD: true
        dcgm:
          enabled: true
        gfd: {}
        dcgmExporter:
          config:
            name: ''
        driver:
          licensingConfig:
            nlsEnabled: false
            configMapName: ''
          certConfig:
            name: ''
          kernelModuleConfig:
            name: ''
          repoConfig:
            configMapName: ''
          virtualTopology:
            config: ''
          enabled: true
          use_ocp_driver_toolkit: true
        devicePlugin: {}
        mig:
          strategy: single
        validator:
          plugin:
            env:
              - name: WITH_WORKLOAD
                value: 'true'
        nodeStatusExporter:
          enabled: true
        daemonsets: {}
        toolkit:
          enabled: true