---

# - name: Get ROSA cluster api url from terraform outputs
#   command: "terraform output -json"
#   args:
#     chdir: "{{ terraform_dir }}"
#   register: tf_output

# - name: extract ROSA section
#   set_fact:
#     rosa_output: "{{ tf_output.stdout | from_json | json_query('rosa') }}"

# - name: Convert ROSA output to valid JSON
#   set_fact:
#     rosa_json: >-
#       {{
#         rosa_output | to_json | replace('=', ':') | replace('tolist(', '') | replace(')', '') | from_json
#       }}

# - name: Extract cluster_api_url
#   set_fact:
#     cluster_api_url: "{{ rosa_json.value.cluster_api_url }}"

- name: Debug cluster_api_url
  ansible.builtin.debug:
    msg: "Cluster API URL: {{ cluster_api_url }}"

- name: Login to OCP cluster
  community.okd.openshift_auth:
    host: "{{ cluster_api_url }}"
    username: "{{ admin_user }}"
    password: "{{ admin_pw }}"
    # verify_ssl: false
  register: login
  retries: 10
  delay: 60

- name: Check openshift version
  kubernetes.core.k8s_info:
    host: "{{ login.openshift_auth.host }}"
    api_key: "{{ login.openshift_auth.api_key }}"
    kind: clusterversion
    name: version
    api_version: config.openshift.io/v1
  register: _ocp_version
  # failed_when: false
  # retries: 5
  # delay: 60

  # no_log: true

- name: Set OpenShift version fact
  ansible.builtin.set_fact:
    ocp_version: "{{ _ocp_version.resources[0].status.desired.version }}"
  # no_log: true

# - fail:
#     msg: |
#       apiVersion: -
#       {{ _ocp_version.resources[0].status.desired.version | to_nice_yaml }}
#       {{ ocp_version is version('4.15', '<') }}

- name: Include installation tasks for components
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - install_other_operators.yaml
    - install_nfd.yaml
    - install_nvidia_gpu_operator.yaml
    - install_rhoai.yaml
  vars:
    kubeconfig: "{{ login.openshift_auth }}"
    api_key: "{{ login.openshift_auth.api_key }}"
    host: "{{ login.openshift_auth.host }}"

- name: Display OpenShift login information
  ansible.builtin.debug:
    msg: |
      OpenShift info

      To log into the cluster run:

        oc login {{ cluster_api_url }} --username "{{ admin_user }}" --password '{{ admin_pw }}'

      The Red Hat OpenShift AI url is:

        https://{{ rhoai_route }}
