---

- name: Check openshift version
  kubernetes.core.k8s_info:
    kind: clusterversion
    name: version
    api_version: config.openshift.io/v1
  register: _ocp_version_info


- name: Set OpenShift version fact
  ansible.builtin.set_fact:
    _ocp_version: "{{ _ocp_version_info.resources[0].status.desired.version }}"

- name: Include installation tasks for components
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - install_other_operators.yaml
    - install_nfd.yaml

- name: Deploy NVidia GPU Operator
  when: install_rhoai_components_nvidia_gpus | bool
  ansible.builtin.include_tasks: install_nvidia_gpu_operator.yaml

- name: Deploy Intel GPU Operator
  when: install_rhoai_components_intel_gpus | bool
  ansible.builtin.include_tasks: install_intel_gpu_operator.yaml

- name: Deploy OpenShift AI
  ansible.builtin.include_tasks: install_rhoai.yaml

- name: Display OpenShift login information
  ansible.builtin.debug:
    msg: |
      OpenShift info

      To log into the cluster run:

        oc login {{ install_rhoai_components_cluster_api_url }} --username "{{ install_rhoai_components_admin_user }}" --password '{{ install_rhoai_components_admin_pw }}'

      The Red Hat OpenShift AI url is:

        https://{{ rhoai_route | default('TBD') }}
